config/routes.rb
Patients::Application.routes.draw do
  get "hospital/index"

  scope '(:locale)' do
    resources :locations

    resources :patients do
      collection do
        get 'ontreatment'
      end
    end

   root :to => 'hospital#index', :as => 'hospital'
  end

end

app/models/location.rb
class Location < ActiveRecord::Base
  attr_accessible :code, :name


  validates :name, :presence => true
  validates :code, :length => {:maximum => 10}
  validates :name, :length => {:maximum => 80}


  has_many :patients

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  attr_accessible :birthday, :first_name, :gender, :isdelete, :last_name, :location_id, :middle_name, :status, :viewed_count
  belongs_to :location
  validates :first_name, :last_name, :status, :location_id, :presence => true
  validates_length_of :first_name, :maximum => 30, :message => "Are you sure the length of your first name?"
  validates_length_of :middle_name, :maximum => 10, :message => "Are you sure the length of your middle name?"
  validates_length_of :last_name, :maximum => 30, :message => "Are you sure the length of your last name?"

  scope :onTreatment,  where(:status => 'Treatment', :isdelete => 0)

  scope :isExist, where(:isdelete => 0)

  def self.fullname(patient)
    [patient.first_name, patient.middle_name, patient.last_name].join(" ")
  end

  def self.mr_number(patient)
  	"MR0000" + patient.id.to_s()
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :set_i18n_locale_from_params

  protected
  	def set_i18n_locale_from_params
  		if params[:locale]
  			if I18n.available_locales.include?(params[:locale].to_sym)
  				I18n.locale = params[:locale]
			else
				flash.now[:notice] = 
				"#{params[:locale]} translation not available"
				logger.error flash.now[:notice]
			end
		end
	end

	def default_url_options
		{ :locale => I18n.locale }
	end
end

app/controllers/hospital_controller.rb
class HospitalController < ApplicationController
  def index
  	if params[:set_locale]
  		redirect_to patients_path(:locale => params[:set_locale])
  	else
  		redirect_to patients_path
  	end
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.json
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to @location, notice: 'Location was successfully created.' }
        format.json { render json: @location, status: :created, location: @location }
      else
        format.html { render action: "new" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.json
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to locations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  # GET /patients
  # GET /patients.json
  def index
    if Location.all.any?
      puts "Data exit!"
    else
      location1 = Location.new(:code => "00001", :name => "Test localtion 1")
      location2 = Location.new(:code => "00002", :name => "Test localtion 2")
      location1.save
      location2.save
    end
    @patients = Patient.isExist

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @patients }
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @patient = Patient.find(params[:id])
    @patient.viewed_count += 1
    @patient.save

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/new
  # GET /patients/new.json
  def new
    @patient = Patient.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/1/edit
  def edit
    @patient = Patient.find(params[:id])
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(params[:patient])
    @patient.viewed_count = 0
    @patient.isdelete = 0

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render json: @patient, status: :created, location: @patient }
      else
        format.html { render action: "new" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patients/1
  # PUT /patients/1.json
  def update
    @patient = Patient.find(params[:id])

    respond_to do |format|
      if @patient.update_attributes(params[:patient])
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient = Patient.find(params[:id])
    @patient.isdelete = 1
    @patient.save

    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end


   # Get /patients/ontreatment
  def ontreatment
    @patients = Patient.onTreatment

    respond_to do |format|
      format.html 
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hospital_helper.rb
module HospitalHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Patients</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id = "patient">
	<div id = "banner">
		<%= form_tag hospital_path, :class => 'locale' do %>
		<%= select_tag 'set_locale',
			options_for_select(LANGUAGES, I18n.locale.to_s),
			:onchange => 'this.form.submit()' %>
			<%= submit_tag 'submit' %>
			<%= javascript_tag "$$('.locale input').each(Element.hide)"%>
		<% end %>
		<%= image_tag("logo.bmp") %>
		<%= @page_tittle || I18n.t('.title') %>
	</div>
	<div id = "columns">
		<div id = "side">
			<%= link_to I18n.t('.locationmanage'),locations_path %><br />
			<%= link_to I18n.t('.patientmanage'),patients_path %><br />
			<%= link_to I18n.t('.ontreatment'),{:action => "ontreatment",
			 :controller => "patients"} %>
		</div>
		<div id = "main">
			<%= yield %>
		</div>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br />
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<h1>Listing locations</h1>

<table>
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.code %></td>
    <td><%= location.name %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Location', new_location_path %>

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Code:</b>
  <%= @location.code %>
</p>

<p>
  <b>Name:</b>
  <%= @location.name %>
</p>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :middle_name %><br />
    <%= f.text_field :middle_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br />
    <%= f.date_select :birthday,:start_year => 1950 %>
  </div>
  <div class="field"> 
    <%= f.label :Gender %><br />
    <%= radio_button "patient", "gender",0%>
    <%= f.label :Male %>
    <%= radio_button "patient", "gender",1 %>
    <%= f.label :Female %>
    <%= radio_button "patient", "gender",2 %>
    <%= f.label :Other %>
  </div>
  <div class="field">
    <%= f.label :Status %><br />
    <%= select "patient","status", options_for_select([ "Initial", 
      "Referred", "Treatment", "Closed" ], "Initial") %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br />
    <%= select  "patient", "location_id",      
        Location.all.collect {|p| [ p.name, p.id ] },  
        { :include_blank => true } %>
  </div>  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<div id="patient_list">
    <h1>Listing patients</h1>

    <table>

    <% @patients.each do |patient| %>
      <tr class="<%= cycle('list_line_odd','list_line_even') %>">
        <td  class = "list_description">
            <b>MR Number: </b>
            <%= Patient.mr_number(patient) %><br />
            <b><%= I18n.t('patients.index.fullname') %></b>
            <%= Patient.fullname(patient) %><br />
            <b>Age: </b>
            <%= Time.now.year - patient.birthday.year + 1 %><br />
            <b>Gender: </b>
            <% if patient.gender = 1 -%>Female
            <% elsif @patient.gender == 0-%>
                Male
            <% else -%>
                Other
            <% end -%><br />
            <b>Status: </b>
            <%= patient.status %><br />
            <b>Viewed count: </b>
            <%= patient.viewed_count %><br />
            <b>Location: </b>
            <%= link_to patient.location.name, patient.location %></td>
        <td class="list_action">
            <%= link_to 'View', patient %><br />
            <%= link_to 'Edit', edit_patient_path(patient) %><br />
            <%= link_to 'Delete', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </table>
</div>
<br />

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/ontreatment.html.erb
<h1>Patients onTreatment</h1>
<table>

    <% @patients.each do |patient| %>
      <tr class="<%= cycle('list_line_odd','list_line_even') %>">
        <td>
            <b>MR Number: </b>
            <%= Patient.mr_number(patient) %><br />
            <b>Full Name: </b>
            <%= Patient.fullname(patient) %><br />
            <b>Birthday: </b>
            <%= patient.birthday %><br />
            <b>Gender: </b>
            <% if patient.gender = 1 -%>Female
            <% else -%>Male
            <% end -%><br />
            <b>Status: </b>
            <%= patient.status %><br />
            <b>Viewed count: </b>
            <%= patient.viewed_count %><br />
            <b>Location: </b>
            <%= link_to patient.location.name, patient.location %></td>
        <td class="list_action">
            <%= link_to 'View', patient %><br />
            <%= link_to 'Edit', edit_patient_path(patient) %><br />
            <%= link_to 'Delete', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </table>


<%= link_to 'New', new_patient_path, :class => 'btn btn-primary' %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>MR Number: </b>
  <%= Patient.mr_number(@patient) %><br />
</p>

<p>
  <b>Full name:</b>
  <%= Patient.fullname(@patient) %><br />
</p>

<p>
  <b>Age:</b>
  <%= Time.now.year - @patient.birthday.year + 1 %>
</p>
<p>
  <b>Gender:</b>
  <% if @patient.gender == 1 -%>
      Female
  <% elsif @patient.gender == 0-%>
      Male
  <% else -%>
      Other
  <% end -%>
</p>

<p>
  <b>Status:</b>
  <%= @patient.status %>
</p>

<p>
  <b>Viewed count:</b>
  <%= @patient.viewed_count %>
</p>

<p>
  <b>Location:</b>
  <%= @patient.location.name %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>